name: SleepWell
options:
  bundleIdPrefix: com.han.sleepwell
  deploymentTarget:
    iOS: 16.6

targets:
  SleepWell:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "Widgets/**"
      - path: Shared
        optional: true
      - Resources
      - Assets.xcassets
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.han.sleepwell.app
        DEVELOPMENT_TEAM: "" # 需要填写您的开发团队 ID
        CODE_SIGN_ENTITLEMENTS: SleepWell.entitlements
        INFOPLIST_FILE: Info.plist
        INFOPLIST_KEY_CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        INFOPLIST_KEY_CFBundleExecutable: $(EXECUTABLE_NAME)
        INFOPLIST_KEY_CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        INFOPLIST_KEY_CFBundleInfoDictionaryVersion: "6.0"
        INFOPLIST_KEY_CFBundleName: $(PRODUCT_NAME)
        INFOPLIST_KEY_CFBundlePackageType: APPL
        INFOPLIST_KEY_CFBundleShortVersionString: "1.0"
        INFOPLIST_KEY_CFBundleVersion: "1"
        INFOPLIST_KEY_NSAppTransportSecurity_NSAllowsArbitraryLoads: true
        INFOPLIST_KEY_NSHealthShareUsageDescription: "需要访问您的健康数据以记录和分析睡眠情况"
        INFOPLIST_KEY_NSHealthUpdateUsageDescription: "需要写入睡眠数据到健康应用"
        INFOPLIST_KEY_UIBackgroundModes: audio,processing,fetch
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDarkContent
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationLandscapeLeft,UIInterfaceOrientationLandscapeRight,UIInterfaceOrientationPortrait
        INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_BGTaskSchedulerPermittedIdentifiers: com.han.sleepwell2024.ios.refresh,com.han.sleepwell2024.ios.processing
        INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
        INFOPLIST_KEY_UIApplicationSceneManifest_UIApplicationSupportsMultipleScenes: false
        INFOPLIST_KEY_UIApplicationSceneManifest_UISceneConfigurations_UIWindowSceneSessionRoleApplication_0_UISceneConfigurationName: Default Configuration
        INFOPLIST_KEY_UIApplicationSceneManifest_UISceneConfigurations_UIWindowSceneSessionRoleApplication_0_UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
        INFOPLIST_KEY_NSSupportsLiveActivities: true
        INFOPLIST_KEY_NSSupportsLiveActivitiesFrequentUpdates: true

  SleepWellTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.han.sleepwell.SleepWellTests
    dependencies:
      - target: SleepWell

  SleepWellUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - Tests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.han.sleepwell.SleepWellUITests
    dependencies:
      - target: SleepWell 